### ISSUE TITLE
Bug: Time precision difference with JS validator worker & Rust Sentry

### ISSUE THREAD

**Issue by samparsky** [AdExNetwork/adex-validator-stack-rust#256]
Ther is a weird time bug in the producer.tick while testing against the  Rust sentry node

`new Date(`) in Javascript precision is less than Utc::now() in Rust

This leads to cases where an aggr time that's meant to be in past is in the future  and Accounting  that's meant to be in the future in the past.

For example if a date is timestamp": "2020-02-17T10:33:03.74612Z from Rust, JS truncates it to  timestamp": "2020-02-17T10:33:03.74Z
which leads to problem because the truncated time is now is in the past and 74612Z > 74Z
Another example is new Date('2020-02-17T11:17:54.332044Z') => 2020-02-17T11:17:54.332Z  in javascript

**Comment by elpiel** [comment]
I looked at the JS Date and chrono, indeed I managed to get the milliseconds in the example `2020-02-17T10:33:03.74612Z` down to `746` in JS.
As one option to solve this I see the variant where we introduce a less accurate Rust DateTime struct impl (in order to manage the (de)serialization).

What suggestions do you have @samparsky to solve this?
I in particular don't want to strictly fix it for JS or Rust instead I would like to see a general fix (like introducing less accurate Datetime to be used across the whole project). It's still somewhat bound to the limitations of JS, but at least the accuracity will be fixed for the whole project. Not sure how it will work with JS sending to Rust more accurate DateTimes.

**Comment by samparsky** [comment]
We can't "fix" it for JS, the Rust impl has to follow the JS impl.
We can make the changes at
- Database level
- Custom serializer for DateTime types
